In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.5.3


In [2]:
# Create 1D array
array_1d = np.array([10, 20, 30, 40, 50])

# Create 2D array
array_2d = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# Create 3D array
array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D Array:")
print(array_1d)
print("Shape:", array_1d.shape)

print("\n2D Array:")
print(array_2d)
print("Shape:", array_2d.shape)

print("\n3D Array:")
print(array_3d)
print("Shape:", array_3d.shape)

1D Array:
[10 20 30 40 50]
Shape: (5,)

2D Array:
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [3]:
# Vectorized operations

numbers = np.array([1, 2, 3, 4, 5])

print("Original:", numbers)
print("Add 10:", numbers + 10)
print("Multiply by 2:", numbers * 2)
print("Square:", numbers ** 2)

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("\nMatrix:")
print(matrix)

print("\nSum of all values:", np.sum(matrix))
print("Sum across rows:", np.sum(matrix, axis=1))
print("Sum across columns:", np.sum(matrix, axis=0))
print("Mean of all values:", np.mean(matrix))

Original: [1 2 3 4 5]
Add 10: [11 12 13 14 15]
Multiply by 2: [ 2  4  6  8 10]
Square: [ 1  4  9 16 25]

Matrix:
[[10 20 30]
 [40 50 60]]

Sum of all values: 210
Sum across rows: [ 60 150]
Sum across columns: [50 70 90]
Mean of all values: 35.0


In [4]:
# Boolean masking

data = np.array([10, 25, 30, 45, 50, 65, 70])

mask = data > 40
print("Values greater than 40:", data[mask])

even_values = data[data % 2 == 0]
print("Even values:", even_values)

# Fancy indexing

selected_values = data[[0, 2, 5]]
print("Values at indexes 0, 2 and 5:", selected_values)

Values greater than 40: [45 50 65 70]
Even values: [10 30 50 70]
Values at indexes 0, 2 and 5: [10 30 65]


In [5]:
# Statistical measures

statistics_data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

mean_value = np.mean(statistics_data)
std_value = np.std(statistics_data)
percentile_50 = np.percentile(statistics_data, 50)
percentile_90 = np.percentile(statistics_data, 90)

print("Mean:", mean_value)
print("Standard deviation:", std_value)
print("50th percentile:", percentile_50)
print("90th percentile:", percentile_90)

# Correlation

x = np.array([10, 20, 30, 40, 50])
y = np.array([20, 40, 60, 80, 100])

correlation_matrix = np.corrcoef(x, y)

print("\nCorrelation matrix:")
print(correlation_matrix)

print("Correlation between x and y:", correlation_matrix[0, 1])

Mean: 55.0
Standard deviation: 28.722813232690143
50th percentile: 55.0
90th percentile: 91.0

Correlation matrix:
[[1. 1.]
 [1. 1.]]
Correlation between x and y: 1.0


In [6]:
# NumPy performance vs Python loop

import time

large_data = np.arange(1_000_000)

# Python loop
start_time = time.perf_counter()

loop_result = [value * 2 for value in large_data]

loop_time = time.perf_counter() - start_time

# NumPy vectorization
start_time = time.perf_counter()

numpy_result = large_data * 2

numpy_time = time.perf_counter() - start_time

print("Number of values:", len(large_data))
print(f"Python loop time: {loop_time:.6f} seconds")
print(f"NumPy vectorized time: {numpy_time:.6f} seconds")

if numpy_time > 0:
    speedup = loop_time / numpy_time
    print(f"NumPy speedup: {speedup:.2f}x faster")

print("Results match:", np.array_equal(
    np.array(loop_result),
    numpy_result
))

Number of values: 1000000
Python loop time: 0.195178 seconds
NumPy vectorized time: 0.002305 seconds
NumPy speedup: 84.66x faster
Results match: True
